name: Unit tests
on:
  workflow_call:
  workflow_run:
    workflows: [Crowdin Action]
    types: [completed]
jobs:
  test:
    timeout-minutes: 20
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dangerous-git-checkout
      - uses: ./.github/actions/yarn-install
      # Should be an 8GB machine as per https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
      - name: Run unit tests
        uses: koenhagen/measure-energy-action@v0.33
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: yarn test
          count: 1
